### ISSUE TITLE
Setup React Router

### ISSUE THREAD

**Issue by tricia-holmes** [Apres-Ski/Apres-Ski-FE#19]
_This can only be set up once we have `landing, demo, main` setup_

**Comment by MattWalterTX** [comment]
Required components are set up. Just calling dibs since Tricia headed the App and Redux and Ryan the Map so I can pull my weight a bit more.

**Comment by tricia-holmes** [comment]
@MattWalterTX Hey Matt! What version of React Router are you planning on using for this?

**Comment by MattWalterTX** [comment]
Hmm, not sure offhand. I have just installed and ran with it in the past. I think its been version... 6??

**Comment by MattWalterTX** [comment]
Yes, 6.6.1/2 on my last couple of projects
